Feature('Scenarios/03ExploreBackendFunctionality');

// Before((I, loginAs) => { // or Background
//     loginAs('vendor'); 
//   });

Scenario('test something', (I, loginAs) => {
  // I.loginAsAdmin();
  loginAs('admin');
  I.amOnPage('/wp-admin');
    	I.click('Dokan');
    	   I.waitForElement('.widgets-wrapper');
          I.checkWarningFatalNotice();
           I.see('At a Glance');
           I.see('Overview');
           I.see('Dokan News Updates');
      I.click('Modules');
            I.waitForElement('.module-content');
            I.checkWarningFatalNotice();
            // I.seeElement('.displaying-num','26 items');
        // Activate all modules
            I.click('#view-switch-list');
            I.wait(5);
            I.click('//input[@type="checkbox"]');
            I.selectOption('#bulk-action-selector-top','Activate');
            I.click('Apply');
            I.wait(5);
    	I.click('Withdraw');
            I.waitForElement('.withdraw-requests');
            I.checkWarningFatalNotice();
    	I.click('Vendors');
            I.waitForElement('.vendor-list');
            I.checkWarningFatalNotice();
            // I.see('Add New');
            // I.seeElement('#post-search-input');
    	I.click('Abuse Reports');
            I.waitForElement('#vue-backend-app');
            I.checkWarningFatalNotice();
            // I.seeElement('//div[@class="tablenav top"]');
    	I.amOnPage('/wp-admin/admin.php?page=dokan#/store-reviews');
    	// I.click('//li[@id="toplevel_page_dokan"]/ul/li[6]/a','Store Reviews');
    	// I.waitForElement('.dokan-store-reviews');
            I.waitForElement('.dokan-store-reviews');
            I.checkWarningFatalNotice();
    	I.click('Announcements');
            I.waitForElement('.dokan-announcement-wrapper');
            I.checkWarningFatalNotice();
    	I.click('Refunds');
            I.waitForElement('.dokan-refund-wrapper');
            I.checkWarningFatalNotice();
    	I.click('Reports');
            I.waitForElement('#vue-backend-app');
            I.checkWarningFatalNotice();
            I.click('All Logs');
                I.waitForElement('#vue-backend-app');
                I.checkWarningFatalNotice();
    	I.click('Tools');
            I.waitForElement('.tools-page');
            I.checkWarningFatalNotice();
    	// I.click('Subscriptions');
      //       I.waitForElement('.subscription-list');
      //       I.checkWarningFatalNotice();
    	I.click('Verifications');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
    	I.click('Wholesale Customer');
            I.waitForElement('.wholesale-customer-list');
            I.checkWarningFatalNotice();
    	I.click('Help');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
        // I.amOnPage('/wp-admin/admin.php?page=dokan#/settings');
    	I.click('Settings');
            I.waitForElement('#dokan_general');
            I.checkWarningFatalNotice();
            // I.click('Save Changes');
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Selling Options');
        I.waitForElement('#dokan_selling');
        I.checkWarningFatalNotice();
            // I.click('Save Changes'); 
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Withdraw Options');
            I.waitForElement('#dokan_withdraw');
            I.checkWarningFatalNotice();
            // I.click('Save Changes');
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Page Settings');
        I.waitForElement('#dokan_pages');
        I.checkWarningFatalNotice();
        I.click('//a[5]');
            I.waitForElement('#dokan_appearance');
            I.checkWarningFatalNotice();
        I.click('Privacy Policy');
            I.waitForElement('#dokan_privacy');
            I.checkWarningFatalNotice();
        I.click('Seller Verification');
            I.waitForElement('#dokan_verification');
            I.checkWarningFatalNotice();
        I.click('Verification SMS Gateways');
            I.waitForElement('#dokan_verification_sms_gateways');
            I.checkWarningFatalNotice();
        I.click('Colors');
            I.waitForElement('#dokan_colors');
            I.checkWarningFatalNotice();
        I.click('Email Verification');
            I.waitForElement('#dokan_email_verification');
            I.checkWarningFatalNotice();
        I.click('Social API');
            I.waitForElement('#dokan_social_api');
            I.checkWarningFatalNotice();        
        I.click('Live Chat');
            I.waitForElement('#dokan_live_chat');
            I.checkWarningFatalNotice();
        I.click('RMA');
            I.waitForElement('#dokan_rma');
            I.checkWarningFatalNotice();
        I.click('Wholesale');
            I.waitForElement('#dokan_wholesale');
            I.checkWarningFatalNotice();
        I.click('Geolocation');
            I.waitForElement('#dokan_geolocation');
            I.checkWarningFatalNotice();
        I.click('Product Report Abuse');
            I.waitForElement('#dokan_report_abuse');
            I.checkWarningFatalNotice();
        I.click('Single Product MultiVendor');
            I.waitForElement('#dokan_spmv');
            I.checkWarningFatalNotice();
        I.click('Product Subscription');
            I.waitForElement('#dokan_product_subscription');
            I.checkWarningFatalNotice();
        /*I.click('Vendor Analytics');
            I.waitForElement('#dokan_vendor_analytics');
            I.checkWarningFatalNotice();*/

});
